/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalculateRouteImport } from './routes/calculate'
import { Route as IndexRouteImport } from './routes/index'

const CalculateRoute = CalculateRouteImport.update({
  id: '/calculate',
  path: '/calculate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculate': typeof CalculateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculate': typeof CalculateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculate': typeof CalculateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calculate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculate'
  id: '__root__' | '/' | '/calculate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculateRoute: typeof CalculateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calculate': {
      id: '/calculate'
      path: '/calculate'
      fullPath: '/calculate'
      preLoaderRoute: typeof CalculateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculateRoute: CalculateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
